export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SHOW_DETAILS = "SHOW_DETAILS";
export const ADD_FAVORITES = "ADD_FAVORITES";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const LIST_FAVORITES = "LIST_FAVORITES";
export const LIST_MOVIES = "LIST_MOVIES";